server:
  port: ${SERVER_PORT:9090}

spring:
  application:
    name: banking-fintech-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:banking_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Avanish@123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000 # 1 day
  refresh-token:
    expiration: 604800000 # 7 days

# Logging
logging:
  level:
    com.fintech.banking: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
